### ISSUE TITLE
Zoom is broken in new update

### ISSUE THREAD

**Issue by dasmikko** [wakahuula/xkcdViewer#20]
**Describe the bug**
Zoom is broken.

When trying to pan the comic, it keeps swiping

**To Reproduce**
1. View comic
2. Zoom
3. Try pan the comic
4. It just swipes left or right

**Expected behavior**
Expected I could pan the image

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Latest OOS
 - Version: Latest versoin

**Comment by wakahuula** [comment]
Thanks and sorry for the inconvenience!
I'll look for a fix later today.

**Comment by wakahuula** [comment]
I'd also be happy for a pull request of course! 😊

**Comment by dasmikko** [comment]
I've made a small XKCD comic viewer too, and here is how i did swiping, and zooming. :)

Keep a variable in state for if you are zooming or not.
When zooming set variable to `true` and disable swiping.
When zoomed out to initial zoom level, set variable to `false` and enable swiping again.

Another solution could be enabling swiping when you are zoomed, and have panned to the edge.

**Comment by dasmikko** [comment]
You can find my project here:
https://github.com/dasmikko/xkcd_flutter

**Comment by wakahuula** [comment]
Thanks for the tip! :)

**Comment by wakahuula** [comment]
So I've tried rebuilding the tree without the Dismissible while in a zoomed state, but the photo_view seems to be losing its state which scales the image to its original position.
The dev is working on a controller. I guess I'll wait for that.
