### ISSUE TITLE
Downloading of images failing

### ISSUE THREAD

**Issue by wakahuula** [wakahuula/xkcdViewer#27]
The simple permissions plugin causes some exceptions which prevent downloads.
Fix this by reimplementing it (or using another approach) and optionally add a simple directory picker to let the user choose the download target. This directory has to be editable within the app's settings.

**Comment by Himanshuranjan30** [comment]
I can fix this if you want @wakahuula.

**Comment by wakahuula** [comment]
Sure, go ahead!

**Comment by Himanshuranjan30** [comment]
The Download feature is working now @wakahuula . I will be sending a pull request in october so that it counts for hacktoberfest.

**Comment by wakahuula** [comment]
Cool, thanks @Himanshuranjan30!

**Comment by wakahuula** [comment]
Issue was fixed by @Himanshuranjan30. Thx!
