### ISSUE TITLE
Replace saving to shared prefs

### ISSUE THREAD

**Issue by wakahuula** [wakahuula/xkcdViewer#28]
Switch from shared preferences to SQLite or [Hive](https://pub.dev/packages/hive).
Adding a comic to the favorites should then also store the image, title, alt text and URL for sharing.

**Comment by britannio** [comment]
I'll start working on switching to Hive. If the shared preferences dependancy is completely removed then the app will be closer to supporting web/desktop.

**Comment by britannio** [comment]
Users might not appreciate losing all of their saved comics.

**Comment by wakahuula** [comment]
Thanks, I appreciate the work you're putting in!
