### ISSUE TITLE
Error With Override

### ISSUE THREAD

**Issue by JohnMeyerhoff** [wakahuula/xkcdViewer#35]
Same issue as https://github.com/Baseflow/flutter_cached_network_image/issues/270

Compiler message:
../../../DEV/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method
'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../DEV/flutter/packages/flutter/lib/src/painting/image_provider.dart:574:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^

**Comment by wakahuula** [comment]
Thanks for letting me know @TwoHorus!

**Comment by wakahuula** [comment]
Not able to reproduce this anymore.
