### ISSUE TITLE
Swipe gestures

### ISSUE THREAD

**Issue by wakahuula** [wakahuula/xkcdViewer#5]
Swipe gestures to left and right in the comic view should browse to the previous/next comic.

**Comment by cshannon3** [comment]
Hey, I've been learning flutter for a while and saw your post about this app on the FlutterDev subreddit. Firstly, the app looks great! I also have been trying to understand the BLoC code structure and this app is a great resource. 

I had the same idea about adding the swipe feature and wrote up some code in the last 3 or 4 hours to see if I could figure out how. I'll fork your project and add the code I wrote so far, if you want to check out what I am trying.  I'd love to get your feedback on my code.

Thanks!

**Comment by wakahuula** [comment]
Hi,
I'd be more than happy to see what you came up with! :blush:

I'll look into your implementation later today.

Thanks!
